export enum StatusCodes {
	ACTIVE = "Ativo",
	INACTIVE = "Inativo",
	DELETED = "Excluído",
	PENDING = "Pendente",
	APPROVED = "Aprovado",
	COMPLETED = "Concluído",
	FINISHED = "Finalizado",
	CANCELED = "Cancelado",
	REJECTED = "Rejeitado",
	PROCESSING = "Em Processamento",
	PENDING_APPROVAL = "Pendente de Aprovação",
	PENDING_REVIEW = "Pendente de Revisão",
	PENDING_PAYMENT = "Pendente de Pagamento",
	COMMERCIAL = "Comercial",
	PRODUCTION = "Produção",
	EXPEDITION = "Expedição",
	DELIVERED = "Entregue",
	SHIPPED = "Enviado",
	RETURNED = "Devolvido",
	PCP = "PCP",
}
