export enum StatusCodes {
	ACTIVE = "ativo",
	INACTIVE = "inativo",
	DELETED = "excluído",
	PENDING = "pendente",
	APPROVED = "aprovado",
	COMPLETED = "concluído",
	FINISHED = "finalizado",
	CANCELED = "cancelado",
	REJECTED = "rejeitado",
	PROCESSING = "em processamento",
	PENDING_APPROVAL = "pendente de aprovação",
	PENDING_REVIEW = "pendente de revisão",
	PENDING_PAYMENT = "pendente de pagamento",
	COMMERCIAL = "comercial",
	PRODUCTION = "produção",
	EXPEDITION = "expedição",
	DELIVERED = "entregue",
	SHIPPED = "enviado",
	RETURNED = "devolvido",
	PCP = "pcp",
}
